version: '3'

services:
  redis:
    image: redis:alpine
    restart: always
    ports:
      - 127.0.0.1:63791:6379
    volumes:
      - "/var/lib/marzbot/docker-volumes/redis:/data"
    command: redis-server --appendonly yes --replica-read-only no

  mariadb:
    image: "mariadb:latest"
    restart: always
    ports:
      - 127.0.0.1:33061:3306
    volumes:
      - /var/lib/marzbot/docker-volumes/mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234ggg
      MYSQL_DATABASE: marzbot
      MYSQL_USER: marzbot
      MYSQL_PASSWORD: 1234ggg

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "127.0.0.1:8010:80"
    environment:
      - PMA_HOST=mariadb
